plugins { id 'com.android.application' }

android {
    namespace 'com.michaelstokes.everythingcalculator'
    compileSdk 35
    defaultConfig {
        applicationId 'com.michaelstokes.everythingcalculator'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.2.0'
    }
    buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
}
